### ISSUE TITLE
Example lacks an index.html

### ISSUE THREAD

**Issue by simonh1000** [ProseMirror/prosemirror-example-setup#9]
The final bit of 'glue' is missing! Going to try to work out what is needed but this certainly slows down a new user

**Comment by marijnh** [comment]
This isn't an example repository in that sense. It provides a utility to easily set up a working editor, but it doesn't provide a full example. See the [website](https://prosemirror.net/examples/) for that.

In any case, since this library is distributed as multiple separate packages, you can't just write an index.html that loads them, you also need some kind of bundler or module loader.

**Comment by mpxc8102** [comment]
For others who've stumbled across this like me, I ended up using https://parceljs.org/ and https://prosemirror.net/examples/basic/. Parcel was super easy to set up, I just installed it and then was able to make use of and import the npm modules for ProseMirror without needing to add config like I would have to if I used webpack. Also you can see the example on prosemirror.net has this line: `import {exampleSetup} from "prosemirror-example-setup"`

Beyond that, you just have to add two divs in your index.html, one with the id `editor` and the other with `content`

Thanks for prosemirror @marijnh! It looks awesome so far, really excited to make use of it
